# Generated by Django 4.1.3 on 2022-12-04 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=12)),
                ('phone_code', models.CharField(max_length=3)),
                ('tag', models.CharField(max_length=150)),
                ('timezone', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='MailDis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('mes', models.TextField()),
                ('end_time', models.DateTimeField()),
                ('user_filter_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='fbrq_api.client')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('awaiting', 'Ожидаем отсылку'), ('sending', 'Отсылается...'), ('stop', 'Отсылка завершена')], max_length=50)),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fbrq_api.client')),
                ('maildis_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fbrq_api.maildis')),
            ],
        ),
    ]
