# Generated by Django 4.1.3 on 2022-12-04 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fbrq_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.RemoveField(
            model_name='maildis',
            name='user_filter_id',
        ),
        migrations.AddField(
            model_name='maildis',
            name='tags',
            field=models.ManyToManyField(to='fbrq_api.tags'),
        ),
    ]
