# Generated by Django 4.1.3 on 2022-12-04 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fbrq_api', '0002_tags_remove_maildis_user_filter_id_maildis_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Codes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=3)),
            ],
        ),
        migrations.AddField(
            model_name='maildis',
            name='phone_code',
            field=models.ManyToManyField(to='fbrq_api.codes'),
        ),
    ]
